services:
  etl-app:
    build: .
    command: python src/app.py  # Forzamos que este corra el script ETL
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    env_file:
      - .env

  dashboard:
    build: .
    command: streamlit run src/dashboard.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - ./src:/app/src
    ports:
      - "8501:8501"  # Puerto web de Streamlit
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: usuario_datos
      POSTGRES_PASSWORD: password_secreto
      POSTGRES_DB: base_integrador
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: